SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FRAMERATE = 60
SCREEN_CENTER_X = SCREEN_WIDTH / 2
SCREEN_CENTER_Y = SCREEN_HEIGHT / 2

DRAW_LINE_WIDTH = 2
WHITE_COLOR = (255, 255, 255)
BLACK_COLOR = (0, 0, 0)

ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MIN_RADIUS = 20
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPLIT_SPEED_FACTOR = 1.2

PLAYER_INITIAL_LIVES = 3
PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300
PLAYER_SHOT_SPEED = 500
PLAYER_SHOT_COOLDOWN = 0.3

SHOT_RADIUS = 5